# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-22 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommonOriginModel',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('host', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('power', models.IntegerField()),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('edited_at', models.DateTimeField()),
                ('secret', models.CharField(default='', max_length=32)),
                ('comments', models.TextField(blank=True)),
            ],
        ),
    ]
