# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-22 02:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ymtech', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonCsvDataModel',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='CommonEnvDataModel',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('comments', models.TextField(blank=True)),
                ('initial_speed', models.FloatField(blank=True)),
                ('setting_pressure', models.FloatField(blank=True)),
                ('rotary_inertia', models.FloatField(blank=True)),
                ('sides_count', models.FloatField(blank=True)),
                ('temperature', models.FloatField(blank=True)),
                ('inner_diameter', models.FloatField(blank=True)),
                ('outer_diameter', models.FloatField(blank=True)),
                ('plate_thickness', models.FloatField(blank=True)),
                ('oil_viscosity', models.FloatField(blank=True)),
                ('micro_polarity', models.FloatField(blank=True)),
                ('surface_roughness', models.FloatField(blank=True)),
                ('rough_density', models.FloatField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='commonoriginmodel',
            name='host',
            field=models.GenericIPAddressField(unique=True),
        ),
        migrations.AddField(
            model_name='commonenvdatamodel',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ymtech.CommonOriginModel'),
        ),
    ]
