# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-22 03:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ymtech', '0002_auto_20160822_0257'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commoncsvdatamodel',
            options={'verbose_name': '\u6570\u636e', 'verbose_name_plural': '\u6570\u636e'},
        ),
        migrations.AlterModelOptions(
            name='commonenvdatamodel',
            options={'verbose_name': '\u5b9e\u9a8c', 'verbose_name_plural': '\u5b9e\u9a8c'},
        ),
        migrations.AlterModelOptions(
            name='commonoriginmodel',
            options={'verbose_name': '\u6765\u6e90', 'verbose_name_plural': '\u6765\u6e90'},
        ),
        migrations.RemoveField(
            model_name='commonenvdatamodel',
            name='micro_polarity',
        ),
        migrations.RemoveField(
            model_name='commonoriginmodel',
            name='edited_at',
        ),
        migrations.AddField(
            model_name='commoncsvdatamodel',
            name='comments',
            field=models.TextField(blank=True, verbose_name='\u63cf\u8ff0'),
        ),
        migrations.AddField(
            model_name='commoncsvdatamodel',
            name='dynamic_friction_coefficient',
            field=models.FloatField(blank=True, default=0, verbose_name='\u52a8\u6469\u64e6\u7cfb\u6570'),
        ),
        migrations.AddField(
            model_name='commoncsvdatamodel',
            name='env',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ymtech.CommonEnvDataModel', verbose_name='\u5b9e\u9a8c'),
        ),
        migrations.AddField(
            model_name='commoncsvdatamodel',
            name='index_time',
            field=models.FloatField(blank=True, default=0, verbose_name='\u65f6\u95f4'),
        ),
        migrations.AddField(
            model_name='commoncsvdatamodel',
            name='micro_polarity',
            field=models.FloatField(blank=True, default=0, verbose_name='\u6cb9\u819c\u539a\u5ea6'),
        ),
        migrations.AddField(
            model_name='commoncsvdatamodel',
            name='pressure',
            field=models.FloatField(blank=True, default=0, verbose_name='\u538b\u529b'),
        ),
        migrations.AddField(
            model_name='commoncsvdatamodel',
            name='rough_contact_torque',
            field=models.FloatField(blank=True, default=0, verbose_name='\u7c97\u7cd9\u63a5\u89e6\u626d\u77e9'),
        ),
        migrations.AddField(
            model_name='commoncsvdatamodel',
            name='speed',
            field=models.FloatField(blank=True, default=0, verbose_name='\u8f6c\u901f'),
        ),
        migrations.AddField(
            model_name='commoncsvdatamodel',
            name='torque',
            field=models.FloatField(blank=True, default=0, verbose_name='\u626d\u77e9'),
        ),
        migrations.AddField(
            model_name='commoncsvdatamodel',
            name='viscous_torque',
            field=models.FloatField(blank=True, default=0, verbose_name='\u7c98\u6027\u626d\u77e9'),
        ),
        migrations.AddField(
            model_name='commonenvdatamodel',
            name='initial_micro_polarity',
            field=models.FloatField(blank=True, default=0, verbose_name='\u521d\u59cb\u6cb9\u819c\u539a\u5ea6'),
        ),
        migrations.AlterField(
            model_name='commonenvdatamodel',
            name='comments',
            field=models.TextField(blank=True, verbose_name='\u63cf\u8ff0'),
        ),
        migrations.AlterField(
            model_name='commonenvdatamodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='commonenvdatamodel',
            name='initial_speed',
            field=models.FloatField(blank=True, default=0, verbose_name='\u521d\u59cb\u8f6c\u901f'),
        ),
        migrations.AlterField(
            model_name='commonenvdatamodel',
            name='inner_diameter',
            field=models.FloatField(blank=True, default=0, verbose_name='\u6469\u64e6\u7247\u5185\u5f84'),
        ),
        migrations.AlterField(
            model_name='commonenvdatamodel',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='commonenvdatamodel',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='\u5b9e\u9a8c\u7f16\u53f7'),
        ),
        migrations.AlterField(
            model_name='commonenvdatamodel',
            name='oil_viscosity',
            field=models.FloatField(blank=True, default=0, verbose_name='\u6da6\u6ed1\u6cb9\u7c98\u5ea6'),
        ),
        migrations.AlterField(
            model_name='commonenvdatamodel',
            name='origin',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ymtech.CommonOriginModel', verbose_name='\u6765\u6e90'),
        ),
        migrations.AlterField(
            model_name='commonenvdatamodel',
            name='outer_diameter',
            field=models.FloatField(blank=True, default=0, verbose_name='\u6469\u64e6\u7247\u5916\u5f84'),
        ),
        migrations.AlterField(
            model_name='commonenvdatamodel',
            name='plate_thickness',
            field=models.FloatField(blank=True, default=0, verbose_name='\u6469\u64e6\u7247\u539a\u5ea6'),
        ),
        migrations.AlterField(
            model_name='commonenvdatamodel',
            name='rotary_inertia',
            field=models.FloatField(blank=True, default=0, verbose_name='\u8f6c\u52a8\u60ef\u91cf'),
        ),
        migrations.AlterField(
            model_name='commonenvdatamodel',
            name='rough_density',
            field=models.FloatField(blank=True, default=0, verbose_name='\u7c97\u7cd9\u5bc6\u5ea6'),
        ),
        migrations.AlterField(
            model_name='commonenvdatamodel',
            name='setting_pressure',
            field=models.FloatField(blank=True, default=0, verbose_name='\u8bbe\u5b9a\u538b\u529b'),
        ),
        migrations.AlterField(
            model_name='commonenvdatamodel',
            name='sides_count',
            field=models.FloatField(blank=True, default=0, verbose_name='\u6469\u64e6\u7247\u9762\u6570'),
        ),
        migrations.AlterField(
            model_name='commonenvdatamodel',
            name='surface_roughness',
            field=models.FloatField(blank=True, default=0, verbose_name='\u6469\u64e6\u6750\u8868\u9762\u7c97\u7cd9\u5ea6'),
        ),
        migrations.AlterField(
            model_name='commonenvdatamodel',
            name='temperature',
            field=models.FloatField(blank=True, default=0, verbose_name='\u6e29\u5ea6'),
        ),
        migrations.AlterField(
            model_name='commonoriginmodel',
            name='comments',
            field=models.TextField(blank=True, verbose_name='\u63cf\u8ff0'),
        ),
        migrations.AlterField(
            model_name='commonoriginmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='commonoriginmodel',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='\u542f\u7528'),
        ),
        migrations.AlterField(
            model_name='commonoriginmodel',
            name='host',
            field=models.GenericIPAddressField(unique=True, verbose_name='\u5730\u5740'),
        ),
        migrations.AlterField(
            model_name='commonoriginmodel',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='commonoriginmodel',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='commonoriginmodel',
            name='power',
            field=models.IntegerField(verbose_name='\u4f18\u5148\u7ea7'),
        ),
        migrations.AlterField(
            model_name='commonoriginmodel',
            name='secret',
            field=models.CharField(default='', max_length=32, verbose_name='\u5bc6\u94a5'),
        ),
    ]
