# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-22 04:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ymtech', '0003_auto_20160822_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commoncsvdatamodel',
            name='rough_contact_torque',
        ),
        migrations.RemoveField(
            model_name='commoncsvdatamodel',
            name='viscous_torque',
        ),
    ]
